apiVersion: v1
kind: Pod
metadata:
  name: druid-historical-pod
  labels:
    name: druid-historical-pod
    context: druid-k8s
spec:
  containers:
    -
      name: druid-historical
      image: jkaralus/druid8s-historical:latest
      imagePullPolicy: IfNotPresent
      ports:
        -
          containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: druid-historical-service
  labels:
    name: druid-historical-pod
    context: druid-k8s
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8083
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: druid-historical-pod
    context: druid-k8s
