apiVersion: v1
kind: Pod
metadata:
  name: druid-coordinator-pod
  labels:
    name: druid-coordinator-pod
    context: druid-k8s
spec:
  containers:
    -
      name: druid-coordinator
      image: jkaralus/druid8s-coordinator:latest
      imagePullPolicy: IfNotPresent
      ports:
        -
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: druid-coordinator-service
  labels:
    name: druid-coordinator-pod
    context: druid-k8s
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8081
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: druid-coordinator-pod
    context: druid-k8s
