apiVersion: v1
kind: Pod
metadata:
  name: druid-metadata-mysql-pod
  labels:
    name: druid-metadata-mysql-pod
    context: druid-k8s
spec:
  containers:
    -
      name: druid-metadata-mysql
      image: jkaralus/druid8s-mysql-utf
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_DATABASE
          value: "druid"
          #create druid database
        - name: MYSQL_ROOT_PASSWORD
          value: "supersecretrootpassword123456789!@"
          #TODO use secrets for that
        - name: MYSQL_USER
          value: "druid"
          #TODO better Handling, secret
        - name: MYSQL_PASSWORD
          value: "secret"
          #TODO better Handling, secret
      ports:
        -
          containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: druid-metadata-mysql-service
  labels:
    name: druid-metadata-mysql-pod
    context: druid-k8s
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3306
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: druid-metadata-mysql-pod
    context: druid-k8s
