apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.nodes.historical.name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      name: "{{ .Chart.Name }}-{{ .Values.nodes.historical.name }}-rc"
      app: {{ template "fullname" . }}
  replicas: {{ .Values.nodes.historical.replicaCount }}
  template:
    metadata:
      labels:
        name: "{{ .Chart.Name }}-{{ .Values.nodes.historical.name }}-rc"
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: "{{ .Chart.Name }}-{{ .Values.nodes.historical.name }}"
        image: "{{ .Values.nodes.historical.image.repository }}:{{ .Values.nodes.historical.image.tag }}"
        imagePullPolicy: {{ .Values.nodes.historical.image.pullPolicy }}
        args: ["historical"]
        ports:
        {{range .Values.nodes.historical.service.ports }}
          - containerPort: {{ .port }}
        {{end}}
        #TODO add readiness & liveness probes
        volumeMounts:
          - name: {{ .Values.nodes.historical.dataVolumeClaim }}
            mountPath: {{ .Values.nodes.historical.dataMountPath }}
          - name: {{ .Values.nodes.historical.segmentcacheVolumeClaim }}
            mountPath: {{ .Values.nodes.historical.segmentcacheMountPath }}
          - name: {{ .Values.nodes.historical.configVolumeClaim }}
            mountPath: {{ .Values.nodes.historical.configMountPath }}
        env:
           - name: MYSQL_CONNECT_URI
             valueFrom:
               secretKeyRef:
                 name: {{ .Values.secrets.name }}
                 key: {{ .Values.secrets.key.connectURI }}
           - name: MYSQL_USERNAME
             valueFrom:
               secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.key.user }}
           - name: MYSQL_PASSWORD
             valueFrom:
               secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.key.password }}
           - name: DRUID_XMX
             value: {{ .Values.env.druid_xmx }}
           - name: DRUID_XMS
             value: {{ .Values.env.druid_xms }}
           - name: DRUID_MAXNEWSIZE
             value: {{ .Values.env.druid_maxnewsize }}
           - name: DRUID_NEWSIZE
             value: {{ .Values.env.druid_newsize }}
           - name: S3_STORAGE_BUCKET
             value: {{ .Values.env.s3_storage_bucket }}
           - name: S3_INDEXING_BUCKET
             value: {{ .Values.env.s3_indexing_bucket }}
           - name: S3_ACCESS_KEY
             value: {{ .Values.env.s3_access_key }}
           - name: DRUID_HOSTNAME
             value: {{ .Values.nodes.coordinator.service.name }}
           - name: ZOOKEEPER_HOST
             value: {{ printf "%s-%s" .Release.Name "zookeeper" | trunc 34 }}
      volumes:
      - name: {{ .Values.nodes.historical.dataVolumeClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.druidSegmentDeepStorage }}
      - name: {{ .Values.nodes.historical.segmentcacheVolumeClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.druidSegmentCache }}
      - name: {{ .Values.nodes.historical.configVolumeClaim }}
        configMap:
          name: common-runtime-configmap
          items:
            - key: common.runtime.properties
              path: _common/common.runtime.properties
            - key: "{{ .Values.nodes.historical.name }}.runtime.properties"
              path: historical/runtime.properties
            - key: "{{ .Values.nodes.historical.name }}.jvm.config"
              path: historical/jvm.config
            - key: "{{ .Values.nodes.historical.name }}.main.config"
              path: historical/main.config
      
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodes.historical.service.name }}
  #TODO flexible service Name, configMap
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.nodes.historical.service.type }}
  ports:
  {{range .Values.nodes.historical.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
  {{end}}
  selector:
    name: "{{ .Chart.Name }}-{{ .Values.nodes.historical.name }}-rc"