apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.nodes.middlemanager.name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      name: "{{ .Chart.Name }}-{{ .Values.nodes.middlemanager.name }}-rc"
      app: {{ template "fullname" . }}
  replicas: {{ .Values.nodes.middlemanager.replicaCount }}
  template:
    metadata:
      labels:
        name: "{{ .Chart.Name }}-{{ .Values.nodes.middlemanager.name }}-rc"
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Values.nodes.middlemanager.service.name }}
        image: "{{ .Values.nodes.middlemanager.image.repository }}:{{ .Values.nodes.middlemanager.image.tag }}"
        imagePullPolicy: {{ .Values.nodes.middlemanager.image.pullPolicy }}
        args: ["middleManager"]
        ports:
        {{range .Values.nodes.middlemanager.service.ports }}
          - containerPort: {{ .port }}
        {{end}}
        volumeMounts:
        - name: {{ .Values.nodes.middlemanager.configVolumeClaim }}
          mountPath: {{ .Values.nodes.middlemanager.configMountPath }}
        env:
           - name: MYSQL_CONNECT_URI
             valueFrom:
               secretKeyRef:
                 name: {{ .Values.secrets.name }}
                 key: {{ .Values.secrets.key.connectURI }}
           - name: MYSQL_USERNAME
             valueFrom:
               secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.key.user }}
           - name: MYSQL_PASSWORD
             valueFrom:
               secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.key.password }}
           - name: DRUID_XMX
             value: {{ .Values.env.druid_xmx }}
           - name: DRUID_XMS
             value: {{ .Values.env.druid_xms }}
           - name: DRUID_MAXNEWSIZE
             value: {{ .Values.env.druid_maxnewsize }}
           - name: DRUID_NEWSIZE
             value: {{ .Values.env.druid_newsize }}
           - name: S3_STORAGE_BUCKET
             value: {{ .Values.env.s3_storage_bucket }}
           - name: S3_INDEXING_BUCKET
             value: {{ .Values.env.s3_indexing_bucket }}
           - name: S3_ACCESS_KEY
             value: {{ .Values.env.s3_access_key }}
           - name: DRUID_HOSTNAME
             value: {{ .Values.nodes.coordinator.service.name }}
           - name: ZOOKEEPER_HOST
             value: {{ printf "%s-%s" .Release.Name "zookeeper" | trunc 34 }}
      volumes:
        - name: {{ .Values.nodes.middlemanager.configVolumeClaim }}
          configMap:
            name: common-runtime-configmap
            items:
            - key: common.runtime.properties
              path: _common/common.runtime.properties
            - key: "{{ .Values.nodes.middlemanager.name }}.runtime.properties"
              path: middleManager/runtime.properties
            - key: "{{ .Values.nodes.middlemanager.name }}.jvm.config"
              path: middleManager/jvm.config
            - key: "{{ .Values.nodes.middlemanager.name }}.main.config"
              path: middleManager/main.config
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.nodes.middlemanager.service.name }}
  labels:
    app: druid
spec:
  type: {{ .Values.nodes.middlemanager.service.type }}
  ports:
  {{range .Values.nodes.middlemanager.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    nodePort: {{ .nodePort }}
  {{end}}
  # *.nginx.default.svc.cluster.local
  selector:
    name: middlemanager
