apiVersion: v1
kind: Secret
metadata:
  name: {{ template "druid.secrets.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-35"
type: Opaque
data:
  #base64 encoded "druid"
  user: ZHJ1aWQ=
  #base64 encoded "keepasecret"
  password: a2VlcGFzZWNyZXQ=
  #base64 encoded "jdbc:mysql://mysql_druid:3306/druid?characterEncoding=UTF-8"
  connectURI: amRiYzpteXNxbDovL215c3FsLWRydWlkOjMzMDYvZHJ1aWQ/Y2hhcmFjdGVyRW5jb2Rpbmc9VVRGLTg=
  #base64 encoded "keepasecret"
  mysql-root-password: a2VlcGFzZWNyZXQ=
  ##base64 encoded "druid"
  mysql-database: ZHJ1aWQ=