# Default values for druid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

#TODO remove quickstart stuff

image:
  historical:
    repository: jkaralus/druid8s-historical
    tag: latest
    pullPolicy: IfNotPresent
  quickstart:
    repository: jkaralus/druid8s-quickstart
    tag: latest
    pullPolicy: IfNotPresent
service:
  historical:
    name: historical
    type: ClusterIP
    externalPort: 8083
    internalPort: 8083
  quickstart:
    name: quickstart
    type: NodePort
    port: 9095
  #TODO remove ulgy hotfix
  type: NodePort

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

